/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { appendForm, encodeSimple } from "../lib/encodings.js";
import {
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  UpdateBookCoverByIdRequest,
  UpdateBookCoverByIdRequest$zodSchema,
  UpdateBookCoverByIdResponse,
  UpdateBookCoverByIdResponse$zodSchema,
} from "../models/updatebookcoverbyidop.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Update a book cover by ID
 *
 * @remarks
 * Updates a single book cover
 */
export function booksUpdateBookCoverById(
  client$: SDKCore,
  request: UpdateBookCoverByIdRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    UpdateBookCoverByIdResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  request: UpdateBookCoverByIdRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      UpdateBookCoverByIdResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => UpdateBookCoverByIdRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = new FormData();
  if (payload$.RequestBody.cover !== undefined) {
    if (isBlobLike(payload$.RequestBody.cover)) {
      appendForm(body$, "cover", payload$.RequestBody.cover);
    } else if (isReadableStream(payload$.RequestBody.cover.content)) {
      const buffer = await readableStreamToArrayBuffer(
        payload$.RequestBody.cover.content,
      );
      const contentType =
        getContentTypeFromFileName(payload$.RequestBody.cover.fileName)
        || "application/octet-stream";
      const blob = new Blob([buffer], { type: contentType });
      appendForm(body$, "cover", blob, payload$.RequestBody.cover.fileName);
    } else {
      const contentType =
        getContentTypeFromFileName(payload$.RequestBody.cover.fileName)
        || "application/octet-stream";
      appendForm(
        body$,
        "cover",
        new Blob([payload$.RequestBody.cover.content], { type: contentType }),
        payload$.RequestBody.cover.fileName,
      );
    }
  }

  const pathParams$ = {
    bookId: encodeSimple("bookId", payload$.bookId, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/books/{bookId}/cover")(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    Accept: "*/*",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "updateBookCoverById",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "PUT",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    UpdateBookCoverByIdResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.nil(200, UpdateBookCoverByIdResponse$zodSchema),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
