/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Author,
  Author$inboundSchema,
  Author$Outbound,
  Author$outboundSchema,
} from "./author.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FantasyBook = {
  id?: number | undefined;
  title: string;
  description: string;
  /**
   * Price in USD cents
   */
  price: number;
  category: "Fantasy";
  author: Author;
  coverImage?: string | undefined;
};

/** @internal */
export const FantasyBook$inboundSchema: z.ZodType<
  FantasyBook,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  title: z.string(),
  description: z.string(),
  price: z.number().int(),
  category: z.literal("Fantasy"),
  author: Author$inboundSchema,
  cover_image: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cover_image": "coverImage",
  });
});

/** @internal */
export type FantasyBook$Outbound = {
  id?: number | undefined;
  title: string;
  description: string;
  price: number;
  category: "Fantasy";
  author: Author$Outbound;
  cover_image?: string | undefined;
};

/** @internal */
export const FantasyBook$outboundSchema: z.ZodType<
  FantasyBook$Outbound,
  z.ZodTypeDef,
  FantasyBook
> = z.object({
  id: z.number().int().optional(),
  title: z.string(),
  description: z.string(),
  price: z.number().int(),
  category: z.literal("Fantasy"),
  author: Author$outboundSchema,
  coverImage: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    coverImage: "cover_image",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FantasyBook$ {
  /** @deprecated use `FantasyBook$inboundSchema` instead. */
  export const inboundSchema = FantasyBook$inboundSchema;
  /** @deprecated use `FantasyBook$outboundSchema` instead. */
  export const outboundSchema = FantasyBook$outboundSchema;
  /** @deprecated use `FantasyBook$Outbound` instead. */
  export type Outbound = FantasyBook$Outbound;
}

export function fantasyBookToJSON(fantasyBook: FantasyBook): string {
  return JSON.stringify(FantasyBook$outboundSchema.parse(fantasyBook));
}

export function fantasyBookFromJSON(
  jsonString: string,
): SafeParseResult<FantasyBook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FantasyBook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FantasyBook' from JSON`,
  );
}
