/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FantasyBook,
  FantasyBook$inboundSchema,
  FantasyBook$Outbound,
  FantasyBook$outboundSchema,
} from "./fantasybook.js";
import {
  ProgrammingBook,
  ProgrammingBook$inboundSchema,
  ProgrammingBook$Outbound,
  ProgrammingBook$outboundSchema,
} from "./programmingbook.js";
import {
  SciFiBook,
  SciFiBook$inboundSchema,
  SciFiBook$Outbound,
  SciFiBook$outboundSchema,
} from "./scifibook.js";
import {
  User,
  User$inboundSchema,
  User$Outbound,
  User$outboundSchema,
} from "./user.js";

export const Status = {
  Pending: "pending",
  Shipped: "shipped",
  Delivered: "delivered",
} as const;
export type Status = ClosedEnum<typeof Status>;

export type Product =
  | (ProgrammingBook & { category: "Programming" })
  | (FantasyBook & { category: "Fantasy" })
  | (SciFiBook & { category: "Sci-fi" });

export type Order = {
  id: number;
  date: Date;
  status: Status;
  user: User;
  products: Array<
    | (ProgrammingBook & { category: "Programming" })
    | (FantasyBook & { category: "Fantasy" })
    | (SciFiBook & { category: "Sci-fi" })
  >;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const Product$inboundSchema: z.ZodType<Product, z.ZodTypeDef, unknown> =
  z.union([
    ProgrammingBook$inboundSchema.and(
      z.object({ category: z.literal("Programming") }).transform((v) => ({
        category: v.category,
      })),
    ),
    FantasyBook$inboundSchema.and(
      z.object({ category: z.literal("Fantasy") }).transform((v) => ({
        category: v.category,
      })),
    ),
    SciFiBook$inboundSchema.and(
      z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
        category: v.category,
      })),
    ),
  ]);

/** @internal */
export type Product$Outbound =
  | (ProgrammingBook$Outbound & { category: "Programming" })
  | (FantasyBook$Outbound & { category: "Fantasy" })
  | (SciFiBook$Outbound & { category: "Sci-fi" });

/** @internal */
export const Product$outboundSchema: z.ZodType<
  Product$Outbound,
  z.ZodTypeDef,
  Product
> = z.union([
  ProgrammingBook$outboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  FantasyBook$outboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  SciFiBook$outboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Product$ {
  /** @deprecated use `Product$inboundSchema` instead. */
  export const inboundSchema = Product$inboundSchema;
  /** @deprecated use `Product$outboundSchema` instead. */
  export const outboundSchema = Product$outboundSchema;
  /** @deprecated use `Product$Outbound` instead. */
  export type Outbound = Product$Outbound;
}

export function productToJSON(product: Product): string {
  return JSON.stringify(Product$outboundSchema.parse(product));
}

export function productFromJSON(
  jsonString: string,
): SafeParseResult<Product, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Product$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Product' from JSON`,
  );
}

/** @internal */
export const Order$inboundSchema: z.ZodType<Order, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int(),
    date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    status: Status$inboundSchema,
    user: User$inboundSchema,
    products: z.array(
      z.union([
        ProgrammingBook$inboundSchema.and(
          z.object({ category: z.literal("Programming") }).transform((v) => ({
            category: v.category,
          })),
        ),
        FantasyBook$inboundSchema.and(
          z.object({ category: z.literal("Fantasy") }).transform((v) => ({
            category: v.category,
          })),
        ),
        SciFiBook$inboundSchema.and(
          z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
            category: v.category,
          })),
        ),
      ]),
    ),
  });

/** @internal */
export type Order$Outbound = {
  id: number;
  date: string;
  status: string;
  user: User$Outbound;
  products: Array<
    | (ProgrammingBook$Outbound & { category: "Programming" })
    | (FantasyBook$Outbound & { category: "Fantasy" })
    | (SciFiBook$Outbound & { category: "Sci-fi" })
  >;
};

/** @internal */
export const Order$outboundSchema: z.ZodType<
  Order$Outbound,
  z.ZodTypeDef,
  Order
> = z.object({
  id: z.number().int(),
  date: z.date().transform(v => v.toISOString()),
  status: Status$outboundSchema,
  user: User$outboundSchema,
  products: z.array(
    z.union([
      ProgrammingBook$outboundSchema.and(
        z.object({ category: z.literal("Programming") }).transform((v) => ({
          category: v.category,
        })),
      ),
      FantasyBook$outboundSchema.and(
        z.object({ category: z.literal("Fantasy") }).transform((v) => ({
          category: v.category,
        })),
      ),
      SciFiBook$outboundSchema.and(
        z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
          category: v.category,
        })),
      ),
    ]),
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Order$ {
  /** @deprecated use `Order$inboundSchema` instead. */
  export const inboundSchema = Order$inboundSchema;
  /** @deprecated use `Order$outboundSchema` instead. */
  export const outboundSchema = Order$outboundSchema;
  /** @deprecated use `Order$Outbound` instead. */
  export type Outbound = Order$Outbound;
}

export function orderToJSON(order: Order): string {
  return JSON.stringify(Order$outboundSchema.parse(order));
}

export function orderFromJSON(
  jsonString: string,
): SafeParseResult<Order, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Order$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Order' from JSON`,
  );
}
