/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Author,
  Author$inboundSchema,
  Author$Outbound,
  Author$outboundSchema,
} from "./author.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ProgrammingBook = {
  id?: number | undefined;
  title: string;
  description: string;
  /**
   * Price in USD cents
   */
  price: number;
  category: "Programming";
  author: Author;
  coverImage?: string | undefined;
};

/** @internal */
export const ProgrammingBook$inboundSchema: z.ZodType<
  ProgrammingBook,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  title: z.string(),
  description: z.string(),
  price: z.number().int(),
  category: z.literal("Programming"),
  author: Author$inboundSchema,
  cover_image: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cover_image": "coverImage",
  });
});

/** @internal */
export type ProgrammingBook$Outbound = {
  id?: number | undefined;
  title: string;
  description: string;
  price: number;
  category: "Programming";
  author: Author$Outbound;
  cover_image?: string | undefined;
};

/** @internal */
export const ProgrammingBook$outboundSchema: z.ZodType<
  ProgrammingBook$Outbound,
  z.ZodTypeDef,
  ProgrammingBook
> = z.object({
  id: z.number().int().optional(),
  title: z.string(),
  description: z.string(),
  price: z.number().int(),
  category: z.literal("Programming"),
  author: Author$outboundSchema,
  coverImage: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    coverImage: "cover_image",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProgrammingBook$ {
  /** @deprecated use `ProgrammingBook$inboundSchema` instead. */
  export const inboundSchema = ProgrammingBook$inboundSchema;
  /** @deprecated use `ProgrammingBook$outboundSchema` instead. */
  export const outboundSchema = ProgrammingBook$outboundSchema;
  /** @deprecated use `ProgrammingBook$Outbound` instead. */
  export type Outbound = ProgrammingBook$Outbound;
}

export function programmingBookToJSON(
  programmingBook: ProgrammingBook,
): string {
  return JSON.stringify(ProgrammingBook$outboundSchema.parse(programmingBook));
}

export function programmingBookFromJSON(
  jsonString: string,
): SafeParseResult<ProgrammingBook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProgrammingBook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProgrammingBook' from JSON`,
  );
}
