/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Author,
  Author$inboundSchema,
  Author$Outbound,
  Author$outboundSchema,
} from "./author.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type SciFiBook = {
  id?: number | undefined;
  title: string;
  description: string;
  /**
   * Price in USD cents
   */
  price: number;
  category: "Sci-fi";
  author: Author;
  coverImage?: string | undefined;
};

/** @internal */
export const SciFiBook$inboundSchema: z.ZodType<
  SciFiBook,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  title: z.string(),
  description: z.string(),
  price: z.number().int(),
  category: z.literal("Sci-fi"),
  author: Author$inboundSchema,
  cover_image: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cover_image": "coverImage",
  });
});

/** @internal */
export type SciFiBook$Outbound = {
  id?: number | undefined;
  title: string;
  description: string;
  price: number;
  category: "Sci-fi";
  author: Author$Outbound;
  cover_image?: string | undefined;
};

/** @internal */
export const SciFiBook$outboundSchema: z.ZodType<
  SciFiBook$Outbound,
  z.ZodTypeDef,
  SciFiBook
> = z.object({
  id: z.number().int().optional(),
  title: z.string(),
  description: z.string(),
  price: z.number().int(),
  category: z.literal("Sci-fi"),
  author: Author$outboundSchema,
  coverImage: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    coverImage: "cover_image",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SciFiBook$ {
  /** @deprecated use `SciFiBook$inboundSchema` instead. */
  export const inboundSchema = SciFiBook$inboundSchema;
  /** @deprecated use `SciFiBook$outboundSchema` instead. */
  export const outboundSchema = SciFiBook$outboundSchema;
  /** @deprecated use `SciFiBook$Outbound` instead. */
  export type Outbound = SciFiBook$Outbound;
}

export function sciFiBookToJSON(sciFiBook: SciFiBook): string {
  return JSON.stringify(SciFiBook$outboundSchema.parse(sciFiBook));
}

export function sciFiBookFromJSON(
  jsonString: string,
): SafeParseResult<SciFiBook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SciFiBook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SciFiBook' from JSON`,
  );
}
