/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { booksUpdateBookCoverById } from "../../funcs/booksUpdateBookCoverById.js";
import { UpdateBookCoverByIdRequest$zodSchema } from "../../models/updatebookcoverbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateBookCoverByIdRequest$zodSchema,
};

export const tool$booksUpdateBookCoverById: ToolDefinition<typeof args> = {
  name: "books-update-book-cover-by-id",
  description: `Update a book cover by ID

Updates a single book cover`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await booksUpdateBookCoverById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
