/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { booksGetBookById } from "../../funcs/booksGetBookById.js";
import { GetBookByIdRequest$zodSchema } from "../../models/getbookbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetBookByIdRequest$zodSchema,
};

export const tool$booksGetBookById: ToolDefinition<typeof args> = {
  name: "books-get-book-by-id",
  description: `Get a book by ID

Returns a single book`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await booksGetBookById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
