/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { booksAddBook } from "../../funcs/booksAddBook.js";
import { AddBookRequest$zodSchema } from "../../models/addbookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddBookRequest$zodSchema,
};

export const tool$booksAddBook: ToolDefinition<typeof args> = {
  name: "books-add-book",
  description: `Add a new book

Adds a new book to the bookstore`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await booksAddBook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
