/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the openapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx booksGetAllBooks.example.ts
 */

import { SDK } from "openapi";

const sdk = new SDK();

async function main() {
  const result = await sdk.books.getAllBooks({
    clientID: "<YOUR_CLIENT_ID_HERE>",
    clientSecret: "<YOUR_CLIENT_SECRET_HERE>",
  });

  console.log(result);
}

main().catch(console.error);
