/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersCreateOrder } from "../funcs/ordersCreateOrder.js";
import { ordersGetAllOrders } from "../funcs/ordersGetAllOrders.js";
import { ordersGetOrderById } from "../funcs/ordersGetOrderById.js";
import { ordersGetOrderStream } from "../funcs/ordersGetOrderStream.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Orders extends ClientSDK {
  /**
   * Get all orders
   *
   * @remarks
   * Returns a list of orders
   */
  async getAllOrders(
    security: operations.GetAllOrdersSecurity,
    options?: RequestOptions,
  ): Promise<Array<models.Order>> {
    return unwrapAsync(ordersGetAllOrders(
      this,
      security,
      options,
    ));
  }

  /**
   * Create a new order
   *
   * @remarks
   * Creates a new order
   */
  async createOrder(
    security: operations.CreateOrderSecurity,
    request: models.NewOrder,
    options?: RequestOptions,
  ): Promise<models.Order> {
    return unwrapAsync(ordersCreateOrder(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get an order by ID
   *
   * @remarks
   * Returns a single order
   */
  async getOrderById(
    security: operations.GetOrderByIdSecurity,
    request: operations.GetOrderByIdRequest,
    options?: RequestOptions,
  ): Promise<models.Order> {
    return unwrapAsync(ordersGetOrderById(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a stream of orders
   *
   * @remarks
   * Returns a stream of orders
   */
  async getOrderStream(
    options?: RequestOptions,
  ): Promise<EventStream<models.OrderStreamMessage>> {
    return unwrapAsync(ordersGetOrderStream(
      this,
      options,
    ));
  }
}
