/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Books } from "./books.js";
import { Orders } from "./orders.js";

export class SDK extends ClientSDK {
  private _books?: Books;
  get books(): Books {
    return (this._books ??= new Books(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }
}
