/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Order, Order$zodSchema } from "./order.js";

export type CreateOrderSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export const CreateOrderSecurity$zodSchema: z.ZodType<
  CreateOrderSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string().describe(
    "OAuth2 Client Credentials Flow client identifier",
  ),
  clientSecret: z.string().describe(
    "OAuth2 Client Credentials Flow client secret",
  ),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token")
    .describe("OAuth2 Client Credentials Flow token URL"),
});

export type CreateOrderResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Order?: Order | undefined;
};

export const CreateOrderResponse$zodSchema: z.ZodType<
  CreateOrderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Order: Order$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
