/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FantasyBook, FantasyBook$zodSchema } from "./fantasybook.js";
import {
  ProgrammingBook,
  ProgrammingBook$zodSchema,
} from "./programmingbook.js";
import { SciFiBook, SciFiBook$zodSchema } from "./scifibook.js";

export type GetAllBooksSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export const GetAllBooksSecurity$zodSchema: z.ZodType<
  GetAllBooksSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string().describe(
    "OAuth2 Client Credentials Flow client identifier",
  ),
  clientSecret: z.string().describe(
    "OAuth2 Client Credentials Flow client secret",
  ),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token")
    .describe("OAuth2 Client Credentials Flow token URL"),
});

export type ResponseBody =
  | (ProgrammingBook & { category: "Programming" })
  | (FantasyBook & { category: "Fantasy" })
  | (SciFiBook & { category: "Sci-fi" });

export const ResponseBody$zodSchema: z.ZodType<
  ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  ProgrammingBook$zodSchema.and(
    z.object({
      category: z.literal("Programming"),
    }).transform((v) => ({ category: v.category })),
  ),
  FantasyBook$zodSchema.and(
    z.object({
      category: z.literal("Fantasy"),
    }).transform((v) => ({ category: v.category })),
  ),
  SciFiBook$zodSchema.and(
    z.object({
      category: z.literal("Sci-fi"),
    }).transform((v) => ({ category: v.category })),
  ),
]);

export type GetAllBooksResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ResponseBodies?:
    | Array<
      | (ProgrammingBook & { category: "Programming" })
      | (FantasyBook & { category: "Fantasy" })
      | (SciFiBook & { category: "Sci-fi" })
    >
    | undefined;
};

export const GetAllBooksResponse$zodSchema: z.ZodType<
  GetAllBooksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  ResponseBodies: z.array(z.union([
    ProgrammingBook$zodSchema.and(
      z.object({
        category: z.literal("Programming"),
      }).transform((v) => ({ category: v.category })),
    ),
    FantasyBook$zodSchema.and(
      z.object({
        category: z.literal("Fantasy"),
      }).transform((v) => ({ category: v.category })),
    ),
    SciFiBook$zodSchema.and(
      z.object({
        category: z.literal("Sci-fi"),
      }).transform((v) => ({ category: v.category })),
    ),
  ])).describe("A list of books").optional(),
  StatusCode: z.number().int(),
});
