/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FantasyBook, FantasyBook$zodSchema } from "./fantasybook.js";
import {
  ProgrammingBook,
  ProgrammingBook$zodSchema,
} from "./programmingbook.js";
import { SciFiBook, SciFiBook$zodSchema } from "./scifibook.js";

/**
 * Book object to be added
 */
export type AddBookRequest =
  | (ProgrammingBook & { category: "Programming" })
  | (FantasyBook & { category: "Fantasy" })
  | (SciFiBook & { category: "Sci-fi" });

export const AddBookRequest$zodSchema: z.ZodType<
  AddBookRequest,
  z.ZodTypeDef,
  unknown
> = z.union([
  ProgrammingBook$zodSchema.and(
    z.object({
      category: z.literal("Programming"),
    }).transform((v) => ({ category: v.category })),
  ),
  FantasyBook$zodSchema.and(
    z.object({
      category: z.literal("Fantasy"),
    }).transform((v) => ({ category: v.category })),
  ),
  SciFiBook$zodSchema.and(
    z.object({
      category: z.literal("Sci-fi"),
    }).transform((v) => ({ category: v.category })),
  ),
]).describe("Book object to be added");

/**
 * Book created successfully
 */
export type AddBookResponseBody =
  | (ProgrammingBook & { category: "Programming" })
  | (FantasyBook & { category: "Fantasy" })
  | (SciFiBook & { category: "Sci-fi" });

export const AddBookResponseBody$zodSchema: z.ZodType<
  AddBookResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  ProgrammingBook$zodSchema.and(
    z.object({
      category: z.literal("Programming"),
    }).transform((v) => ({ category: v.category })),
  ),
  FantasyBook$zodSchema.and(
    z.object({
      category: z.literal("Fantasy"),
    }).transform((v) => ({ category: v.category })),
  ),
  SciFiBook$zodSchema.and(
    z.object({
      category: z.literal("Sci-fi"),
    }).transform((v) => ({ category: v.category })),
  ),
]).describe("Book created successfully");

export type AddBookResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  oneOf?:
    | (ProgrammingBook & { category: "Programming" })
    | (FantasyBook & { category: "Fantasy" })
    | (SciFiBook & { category: "Sci-fi" })
    | undefined;
};

export const AddBookResponse$zodSchema: z.ZodType<
  AddBookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  oneOf: z.union([
    ProgrammingBook$zodSchema.and(
      z.object({
        category: z.literal("Programming"),
      }).transform((v) => ({ category: v.category })),
    ),
    FantasyBook$zodSchema.and(
      z.object({
        category: z.literal("Fantasy"),
      }).transform((v) => ({ category: v.category })),
    ),
    SciFiBook$zodSchema.and(
      z.object({
        category: z.literal("Sci-fi"),
      }).transform((v) => ({ category: v.category })),
    ),
  ]).optional(),
});
