/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AuthorWithID = {
  id: number;
  name?: string | undefined;
  photo?: string | undefined;
  biography?: string | undefined;
};

export const AuthorWithID$zodSchema: z.ZodType<
  AuthorWithID,
  z.ZodTypeDef,
  unknown
> = z.object({
  biography: z.string().optional(),
  id: z.number().int(),
  name: z.string().optional(),
  photo: z.string().optional(),
});

export type AuthorWithName = {
  id?: number | undefined;
  name: string;
  photo?: string | undefined;
  biography?: string | undefined;
};

export const AuthorWithName$zodSchema: z.ZodType<
  AuthorWithName,
  z.ZodTypeDef,
  unknown
> = z.object({
  biography: z.string().optional(),
  id: z.number().int().optional(),
  name: z.string(),
  photo: z.string().optional(),
});

export type Author = AuthorWithName | AuthorWithID;

export const Author$zodSchema: z.ZodType<Author, z.ZodTypeDef, unknown> = z
  .union([
    z.lazy(() => AuthorWithName$zodSchema),
    z.lazy(() => AuthorWithID$zodSchema),
  ]);
