/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Order, Order$zodSchema } from "./order.js";

export type GetAllOrdersSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export const GetAllOrdersSecurity$zodSchema: z.ZodType<
  GetAllOrdersSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string().describe(
    "OAuth2 Client Credentials Flow client identifier",
  ),
  clientSecret: z.string().describe(
    "OAuth2 Client Credentials Flow client secret",
  ),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token")
    .describe("OAuth2 Client Credentials Flow token URL"),
});

export type GetAllOrdersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Orders?: Array<Order> | undefined;
};

export const GetAllOrdersResponse$zodSchema: z.ZodType<
  GetAllOrdersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Orders: z.array(Order$zodSchema).describe("A list of orders").optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
