/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FantasyBook, FantasyBook$zodSchema } from "./fantasybook.js";
import {
  ProgrammingBook,
  ProgrammingBook$zodSchema,
} from "./programmingbook.js";
import { SciFiBook, SciFiBook$zodSchema } from "./scifibook.js";

export type GetBookByIdRequest = { bookId: number };

export const GetBookByIdRequest$zodSchema: z.ZodType<
  GetBookByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  bookId: z.number().int().describe("ID of the book to return"),
});

/**
 * A single book
 */
export type GetBookByIdResponseBody =
  | (ProgrammingBook & { category: "Programming" })
  | (FantasyBook & { category: "Fantasy" })
  | (SciFiBook & { category: "Sci-fi" });

export const GetBookByIdResponseBody$zodSchema: z.ZodType<
  GetBookByIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  ProgrammingBook$zodSchema.and(
    z.object({
      category: z.literal("Programming"),
    }).transform((v) => ({ category: v.category })),
  ),
  FantasyBook$zodSchema.and(
    z.object({
      category: z.literal("Fantasy"),
    }).transform((v) => ({ category: v.category })),
  ),
  SciFiBook$zodSchema.and(
    z.object({
      category: z.literal("Sci-fi"),
    }).transform((v) => ({ category: v.category })),
  ),
]).describe("A single book");

export type GetBookByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  oneOf?:
    | (ProgrammingBook & { category: "Programming" })
    | (FantasyBook & { category: "Fantasy" })
    | (SciFiBook & { category: "Sci-fi" })
    | undefined;
};

export const GetBookByIdResponse$zodSchema: z.ZodType<
  GetBookByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  oneOf: z.union([
    ProgrammingBook$zodSchema.and(
      z.object({
        category: z.literal("Programming"),
      }).transform((v) => ({ category: v.category })),
    ),
    FantasyBook$zodSchema.and(
      z.object({
        category: z.literal("Fantasy"),
      }).transform((v) => ({ category: v.category })),
    ),
    SciFiBook$zodSchema.and(
      z.object({
        category: z.literal("Sci-fi"),
      }).transform((v) => ({ category: v.category })),
    ),
  ]).optional(),
});
