/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Order, Order$zodSchema } from "./order.js";

export type GetOrderByIdSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export const GetOrderByIdSecurity$zodSchema: z.ZodType<
  GetOrderByIdSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string().describe(
    "OAuth2 Client Credentials Flow client identifier",
  ),
  clientSecret: z.string().describe(
    "OAuth2 Client Credentials Flow client secret",
  ),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token")
    .describe("OAuth2 Client Credentials Flow token URL"),
});

export type GetOrderByIdRequest = { orderId: number };

export const GetOrderByIdRequest$zodSchema: z.ZodType<
  GetOrderByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  orderId: z.number().int().describe("ID of the order to return"),
});

export type GetOrderByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Order?: Order | undefined;
};

export const GetOrderByIdResponse$zodSchema: z.ZodType<
  GetOrderByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Order: Order$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
