/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type NewOrder = { user: number; products: Array<number> };

export const NewOrder$zodSchema: z.ZodType<NewOrder, z.ZodTypeDef, unknown> = z
  .object({
    products: z.array(z.number().int()),
    user: z.number().int(),
  });
