/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FantasyBook, FantasyBook$zodSchema } from "./fantasybook.js";
import {
  ProgrammingBook,
  ProgrammingBook$zodSchema,
} from "./programmingbook.js";
import { SciFiBook, SciFiBook$zodSchema } from "./scifibook.js";
import { User, User$zodSchema } from "./user.js";

export const Status$zodSchema = z.enum([
  "pending",
  "shipped",
  "delivered",
]);

export type Status = z.infer<typeof Status$zodSchema>;

export type Product =
  | (ProgrammingBook & { category: "Programming" })
  | (FantasyBook & { category: "Fantasy" })
  | (SciFiBook & { category: "Sci-fi" });

export const Product$zodSchema: z.ZodType<Product, z.ZodTypeDef, unknown> = z
  .union([
    ProgrammingBook$zodSchema.and(
      z.object({
        category: z.literal("Programming"),
      }).transform((v) => ({ category: v.category })),
    ),
    FantasyBook$zodSchema.and(
      z.object({
        category: z.literal("Fantasy"),
      }).transform((v) => ({ category: v.category })),
    ),
    SciFiBook$zodSchema.and(
      z.object({
        category: z.literal("Sci-fi"),
      }).transform((v) => ({ category: v.category })),
    ),
  ]);

export type Order = {
  id: number;
  date: string;
  status: Status;
  user: User;
  products: Array<
    | (ProgrammingBook & { category: "Programming" })
    | (FantasyBook & { category: "Fantasy" })
    | (SciFiBook & { category: "Sci-fi" })
  >;
};

export const Order$zodSchema: z.ZodType<Order, z.ZodTypeDef, unknown> = z
  .object({
    date: z.string().datetime({ offset: true }),
    id: z.number().int(),
    products: z.array(z.union([
      ProgrammingBook$zodSchema.and(
        z.object({
          category: z.literal("Programming"),
        }).transform((v) => ({ category: v.category })),
      ),
      FantasyBook$zodSchema.and(
        z.object({
          category: z.literal("Fantasy"),
        }).transform((v) => ({ category: v.category })),
      ),
      SciFiBook$zodSchema.and(
        z.object({
          category: z.literal("Sci-fi"),
        }).transform((v) => ({ category: v.category })),
      ),
    ])),
    status: Status$zodSchema,
    user: User$zodSchema,
  });
