/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Author, Author$zodSchema } from "./author.js";

export type ProgrammingBook = {
  id?: number | undefined;
  title: string;
  description: string;
  price: number;
  category?: "Programming" | undefined;
  author: Author;
  cover_image?: string | undefined;
};

export const ProgrammingBook$zodSchema: z.ZodType<
  ProgrammingBook,
  z.ZodTypeDef,
  unknown
> = z.object({
  author: Author$zodSchema,
  category: z.literal("Programming").optional(),
  cover_image: z.string().optional(),
  description: z.string(),
  id: z.number().int().optional(),
  price: z.number().int(),
  title: z.string(),
});
