/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = { apiKey?: string | undefined };

export const Security$zodSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
  .object({
    apiKey: z.string().describe("API Key").optional(),
  });
