/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Cover = { fileName: string; content: Uint8Array | string };

export const Cover$zodSchema: z.ZodType<Cover, z.ZodTypeDef, unknown> = z
  .object({
    content: z.string().base64(),
    fileName: z.string(),
  });

/**
 * Book cover
 */
export type UpdateBookCoverByIdRequestBody = {
  cover?: Cover | Blob | undefined;
};

export const UpdateBookCoverByIdRequestBody$zodSchema: z.ZodType<
  UpdateBookCoverByIdRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  cover: z.lazy(() => Cover$zodSchema).optional(),
}).describe("Book cover");

export type UpdateBookCoverByIdRequest = {
  bookId: number;
  RequestBody: UpdateBookCoverByIdRequestBody;
};

export const UpdateBookCoverByIdRequest$zodSchema: z.ZodType<
  UpdateBookCoverByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.lazy(() => UpdateBookCoverByIdRequestBody$zodSchema),
  bookId: z.number().int().describe("ID of the book to update"),
});

export type UpdateBookCoverByIdResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const UpdateBookCoverByIdResponse$zodSchema: z.ZodType<
  UpdateBookCoverByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
