/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type User = {
  id?: number | undefined;
  email?: string | undefined;
  name?: string | undefined;
};

export const User$zodSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z.object({
  email: z.string().optional(),
  id: z.number().int().optional(),
  name: z.string().optional(),
});
