/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Book object to be added
 */
export type AddBookRequest =
  | (models.ProgrammingBook & { category: "Programming" })
  | (models.FantasyBook & { category: "Fantasy" })
  | (models.SciFiBook & { category: "Sci-fi" });

/**
 * Book created successfully
 */
export type AddBookResponse =
  | (models.ProgrammingBook & { category: "Programming" })
  | (models.FantasyBook & { category: "Fantasy" })
  | (models.SciFiBook & { category: "Sci-fi" });

/** @internal */
export const AddBookRequest$inboundSchema: z.ZodType<
  AddBookRequest,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ProgrammingBook$inboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$inboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$inboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/** @internal */
export type AddBookRequest$Outbound =
  | (models.ProgrammingBook$Outbound & { category: "Programming" })
  | (models.FantasyBook$Outbound & { category: "Fantasy" })
  | (models.SciFiBook$Outbound & { category: "Sci-fi" });

/** @internal */
export const AddBookRequest$outboundSchema: z.ZodType<
  AddBookRequest$Outbound,
  z.ZodTypeDef,
  AddBookRequest
> = z.union([
  models.ProgrammingBook$outboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$outboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$outboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddBookRequest$ {
  /** @deprecated use `AddBookRequest$inboundSchema` instead. */
  export const inboundSchema = AddBookRequest$inboundSchema;
  /** @deprecated use `AddBookRequest$outboundSchema` instead. */
  export const outboundSchema = AddBookRequest$outboundSchema;
  /** @deprecated use `AddBookRequest$Outbound` instead. */
  export type Outbound = AddBookRequest$Outbound;
}

export function addBookRequestToJSON(addBookRequest: AddBookRequest): string {
  return JSON.stringify(AddBookRequest$outboundSchema.parse(addBookRequest));
}

export function addBookRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddBookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddBookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddBookRequest' from JSON`,
  );
}

/** @internal */
export const AddBookResponse$inboundSchema: z.ZodType<
  AddBookResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ProgrammingBook$inboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$inboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$inboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/** @internal */
export type AddBookResponse$Outbound =
  | (models.ProgrammingBook$Outbound & { category: "Programming" })
  | (models.FantasyBook$Outbound & { category: "Fantasy" })
  | (models.SciFiBook$Outbound & { category: "Sci-fi" });

/** @internal */
export const AddBookResponse$outboundSchema: z.ZodType<
  AddBookResponse$Outbound,
  z.ZodTypeDef,
  AddBookResponse
> = z.union([
  models.ProgrammingBook$outboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$outboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$outboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddBookResponse$ {
  /** @deprecated use `AddBookResponse$inboundSchema` instead. */
  export const inboundSchema = AddBookResponse$inboundSchema;
  /** @deprecated use `AddBookResponse$outboundSchema` instead. */
  export const outboundSchema = AddBookResponse$outboundSchema;
  /** @deprecated use `AddBookResponse$Outbound` instead. */
  export type Outbound = AddBookResponse$Outbound;
}

export function addBookResponseToJSON(
  addBookResponse: AddBookResponse,
): string {
  return JSON.stringify(AddBookResponse$outboundSchema.parse(addBookResponse));
}

export function addBookResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddBookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddBookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddBookResponse' from JSON`,
  );
}
