/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateOrderSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

/** @internal */
export const CreateOrderSecurity$inboundSchema: z.ZodType<
  CreateOrderSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/** @internal */
export type CreateOrderSecurity$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const CreateOrderSecurity$outboundSchema: z.ZodType<
  CreateOrderSecurity$Outbound,
  z.ZodTypeDef,
  CreateOrderSecurity
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrderSecurity$ {
  /** @deprecated use `CreateOrderSecurity$inboundSchema` instead. */
  export const inboundSchema = CreateOrderSecurity$inboundSchema;
  /** @deprecated use `CreateOrderSecurity$outboundSchema` instead. */
  export const outboundSchema = CreateOrderSecurity$outboundSchema;
  /** @deprecated use `CreateOrderSecurity$Outbound` instead. */
  export type Outbound = CreateOrderSecurity$Outbound;
}

export function createOrderSecurityToJSON(
  createOrderSecurity: CreateOrderSecurity,
): string {
  return JSON.stringify(
    CreateOrderSecurity$outboundSchema.parse(createOrderSecurity),
  );
}

export function createOrderSecurityFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrderSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrderSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrderSecurity' from JSON`,
  );
}
