/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAllOrdersSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

/** @internal */
export const GetAllOrdersSecurity$inboundSchema: z.ZodType<
  GetAllOrdersSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/** @internal */
export type GetAllOrdersSecurity$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const GetAllOrdersSecurity$outboundSchema: z.ZodType<
  GetAllOrdersSecurity$Outbound,
  z.ZodTypeDef,
  GetAllOrdersSecurity
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllOrdersSecurity$ {
  /** @deprecated use `GetAllOrdersSecurity$inboundSchema` instead. */
  export const inboundSchema = GetAllOrdersSecurity$inboundSchema;
  /** @deprecated use `GetAllOrdersSecurity$outboundSchema` instead. */
  export const outboundSchema = GetAllOrdersSecurity$outboundSchema;
  /** @deprecated use `GetAllOrdersSecurity$Outbound` instead. */
  export type Outbound = GetAllOrdersSecurity$Outbound;
}

export function getAllOrdersSecurityToJSON(
  getAllOrdersSecurity: GetAllOrdersSecurity,
): string {
  return JSON.stringify(
    GetAllOrdersSecurity$outboundSchema.parse(getAllOrdersSecurity),
  );
}

export function getAllOrdersSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetAllOrdersSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllOrdersSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllOrdersSecurity' from JSON`,
  );
}
