/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAllBooksSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export type GetAllBooksResponse =
  | (models.ProgrammingBook & { category: "Programming" })
  | (models.FantasyBook & { category: "Fantasy" })
  | (models.SciFiBook & { category: "Sci-fi" });

/** @internal */
export const GetAllBooksSecurity$inboundSchema: z.ZodType<
  GetAllBooksSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/** @internal */
export type GetAllBooksSecurity$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const GetAllBooksSecurity$outboundSchema: z.ZodType<
  GetAllBooksSecurity$Outbound,
  z.ZodTypeDef,
  GetAllBooksSecurity
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllBooksSecurity$ {
  /** @deprecated use `GetAllBooksSecurity$inboundSchema` instead. */
  export const inboundSchema = GetAllBooksSecurity$inboundSchema;
  /** @deprecated use `GetAllBooksSecurity$outboundSchema` instead. */
  export const outboundSchema = GetAllBooksSecurity$outboundSchema;
  /** @deprecated use `GetAllBooksSecurity$Outbound` instead. */
  export type Outbound = GetAllBooksSecurity$Outbound;
}

export function getAllBooksSecurityToJSON(
  getAllBooksSecurity: GetAllBooksSecurity,
): string {
  return JSON.stringify(
    GetAllBooksSecurity$outboundSchema.parse(getAllBooksSecurity),
  );
}

export function getAllBooksSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetAllBooksSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllBooksSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllBooksSecurity' from JSON`,
  );
}

/** @internal */
export const GetAllBooksResponse$inboundSchema: z.ZodType<
  GetAllBooksResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ProgrammingBook$inboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$inboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$inboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/** @internal */
export type GetAllBooksResponse$Outbound =
  | (models.ProgrammingBook$Outbound & { category: "Programming" })
  | (models.FantasyBook$Outbound & { category: "Fantasy" })
  | (models.SciFiBook$Outbound & { category: "Sci-fi" });

/** @internal */
export const GetAllBooksResponse$outboundSchema: z.ZodType<
  GetAllBooksResponse$Outbound,
  z.ZodTypeDef,
  GetAllBooksResponse
> = z.union([
  models.ProgrammingBook$outboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$outboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$outboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllBooksResponse$ {
  /** @deprecated use `GetAllBooksResponse$inboundSchema` instead. */
  export const inboundSchema = GetAllBooksResponse$inboundSchema;
  /** @deprecated use `GetAllBooksResponse$outboundSchema` instead. */
  export const outboundSchema = GetAllBooksResponse$outboundSchema;
  /** @deprecated use `GetAllBooksResponse$Outbound` instead. */
  export type Outbound = GetAllBooksResponse$Outbound;
}

export function getAllBooksResponseToJSON(
  getAllBooksResponse: GetAllBooksResponse,
): string {
  return JSON.stringify(
    GetAllBooksResponse$outboundSchema.parse(getAllBooksResponse),
  );
}

export function getAllBooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllBooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllBooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllBooksResponse' from JSON`,
  );
}
