/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetBookByIdRequest = {
  /**
   * ID of the book to return
   */
  bookId: number;
};

/**
 * A single book
 */
export type GetBookByIdResponse =
  | (models.ProgrammingBook & { category: "Programming" })
  | (models.FantasyBook & { category: "Fantasy" })
  | (models.SciFiBook & { category: "Sci-fi" });

/** @internal */
export const GetBookByIdRequest$inboundSchema: z.ZodType<
  GetBookByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  bookId: z.number().int(),
});

/** @internal */
export type GetBookByIdRequest$Outbound = {
  bookId: number;
};

/** @internal */
export const GetBookByIdRequest$outboundSchema: z.ZodType<
  GetBookByIdRequest$Outbound,
  z.ZodTypeDef,
  GetBookByIdRequest
> = z.object({
  bookId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBookByIdRequest$ {
  /** @deprecated use `GetBookByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetBookByIdRequest$inboundSchema;
  /** @deprecated use `GetBookByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetBookByIdRequest$outboundSchema;
  /** @deprecated use `GetBookByIdRequest$Outbound` instead. */
  export type Outbound = GetBookByIdRequest$Outbound;
}

export function getBookByIdRequestToJSON(
  getBookByIdRequest: GetBookByIdRequest,
): string {
  return JSON.stringify(
    GetBookByIdRequest$outboundSchema.parse(getBookByIdRequest),
  );
}

export function getBookByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetBookByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookByIdRequest' from JSON`,
  );
}

/** @internal */
export const GetBookByIdResponse$inboundSchema: z.ZodType<
  GetBookByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ProgrammingBook$inboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$inboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$inboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/** @internal */
export type GetBookByIdResponse$Outbound =
  | (models.ProgrammingBook$Outbound & { category: "Programming" })
  | (models.FantasyBook$Outbound & { category: "Fantasy" })
  | (models.SciFiBook$Outbound & { category: "Sci-fi" });

/** @internal */
export const GetBookByIdResponse$outboundSchema: z.ZodType<
  GetBookByIdResponse$Outbound,
  z.ZodTypeDef,
  GetBookByIdResponse
> = z.union([
  models.ProgrammingBook$outboundSchema.and(
    z.object({ category: z.literal("Programming") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.FantasyBook$outboundSchema.and(
    z.object({ category: z.literal("Fantasy") }).transform((v) => ({
      category: v.category,
    })),
  ),
  models.SciFiBook$outboundSchema.and(
    z.object({ category: z.literal("Sci-fi") }).transform((v) => ({
      category: v.category,
    })),
  ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBookByIdResponse$ {
  /** @deprecated use `GetBookByIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetBookByIdResponse$inboundSchema;
  /** @deprecated use `GetBookByIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetBookByIdResponse$outboundSchema;
  /** @deprecated use `GetBookByIdResponse$Outbound` instead. */
  export type Outbound = GetBookByIdResponse$Outbound;
}

export function getBookByIdResponseToJSON(
  getBookByIdResponse: GetBookByIdResponse,
): string {
  return JSON.stringify(
    GetBookByIdResponse$outboundSchema.parse(getBookByIdResponse),
  );
}

export function getBookByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBookByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookByIdResponse' from JSON`,
  );
}
