/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrderByIdSecurity = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

export type GetOrderByIdRequest = {
  /**
   * ID of the order to return
   */
  orderId: number;
};

/** @internal */
export const GetOrderByIdSecurity$inboundSchema: z.ZodType<
  GetOrderByIdSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/** @internal */
export type GetOrderByIdSecurity$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const GetOrderByIdSecurity$outboundSchema: z.ZodType<
  GetOrderByIdSecurity$Outbound,
  z.ZodTypeDef,
  GetOrderByIdSecurity
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z.string().default("https://api.bookstore.com/oauth/token"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderByIdSecurity$ {
  /** @deprecated use `GetOrderByIdSecurity$inboundSchema` instead. */
  export const inboundSchema = GetOrderByIdSecurity$inboundSchema;
  /** @deprecated use `GetOrderByIdSecurity$outboundSchema` instead. */
  export const outboundSchema = GetOrderByIdSecurity$outboundSchema;
  /** @deprecated use `GetOrderByIdSecurity$Outbound` instead. */
  export type Outbound = GetOrderByIdSecurity$Outbound;
}

export function getOrderByIdSecurityToJSON(
  getOrderByIdSecurity: GetOrderByIdSecurity,
): string {
  return JSON.stringify(
    GetOrderByIdSecurity$outboundSchema.parse(getOrderByIdSecurity),
  );
}

export function getOrderByIdSecurityFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderByIdSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrderByIdSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderByIdSecurity' from JSON`,
  );
}

/** @internal */
export const GetOrderByIdRequest$inboundSchema: z.ZodType<
  GetOrderByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  orderId: z.number().int(),
});

/** @internal */
export type GetOrderByIdRequest$Outbound = {
  orderId: number;
};

/** @internal */
export const GetOrderByIdRequest$outboundSchema: z.ZodType<
  GetOrderByIdRequest$Outbound,
  z.ZodTypeDef,
  GetOrderByIdRequest
> = z.object({
  orderId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderByIdRequest$ {
  /** @deprecated use `GetOrderByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetOrderByIdRequest$inboundSchema;
  /** @deprecated use `GetOrderByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetOrderByIdRequest$outboundSchema;
  /** @deprecated use `GetOrderByIdRequest$Outbound` instead. */
  export type Outbound = GetOrderByIdRequest$Outbound;
}

export function getOrderByIdRequestToJSON(
  getOrderByIdRequest: GetOrderByIdRequest,
): string {
  return JSON.stringify(
    GetOrderByIdRequest$outboundSchema.parse(getOrderByIdRequest),
  );
}

export function getOrderByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrderByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderByIdRequest' from JSON`,
  );
}
